global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Flask app metrics through Nginx
  - job_name: "flask_app"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: /metrics

  # Scrape container metrics from cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
